(self.AMP=self.AMP||[]).push({n:"amp-form",v:"2010122315000",f:(function(AMP,_){
'use strict';var k,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var ca;
if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var da;a:{var ea={a:!0},fa={};try{fa.__proto__=ea;da=fa.a;break a}catch(a){}da=!1}ca=da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ca;
function m(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Wa=b.prototype}var ia;function p(){return ia?ia:ia=Promise.resolve(void 0)};function ja(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var ka=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function la(a){var b=Object.create(null);if(!a)return b;for(var c;c=ka.exec(a);){var d=ja(c[1],c[1]),e=c[2]?ja(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var ma=Object.prototype.toString;function na(a){return a?Array.prototype.slice.call(a):[]};var q=self.AMP_CONFIG||{},oa=("string"==typeof q.cdnProxyRegex?new RegExp(q.cdnProxyRegex):q.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function pa(a){if(!self.document||!self.document.head||self.location&&oa.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var qa={thirdParty:q.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:q.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof q.thirdPartyFrameRegex?new RegExp(q.thirdPartyFrameRegex):q.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:q.cdnUrl||pa("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:oa,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:q.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:q.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:q.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:q.geoApiUrl||pa("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var r=self.__AMP_LOG;function t(){if(!r.user)throw Error("failed to call initLogConstructor");return r.user}function ra(){if(r.dev)return r.dev;throw Error("failed to call initLogConstructor");}function u(a,b,c,d){t().assert(a,b,c,d,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function sa(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function ta(a){return new Promise(function(b){b(a())})}function ua(){var a,b;this.xa=new Promise(function(c,d){a=c;b=d});this.Ma=a;this.Ka=b;this.ha=0}ua.prototype.add=function(a){var b=this,c=++this.ha;Promise.resolve(a).then(function(a){b.ha===c&&b.Ma(a)},function(a){b.ha===c&&b.Ka(a)});return this.xa};ua.prototype.then=function(a,b){return this.xa.then(a,b)};function v(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return w(a,b)}function x(a,b){var c=y(a);c=z(c);return w(c,b)}function A(a,b){a=y(a);a=z(a);return va(a,b)?w(a,b):null}function wa(a,b){return xa(z(a),b)}function y(a){return a.nodeType?v((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function z(a){a=y(a);return a.isSingleDoc()?a.win:a}function w(a,b){va(a,b);a=ya(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function za(a,b){var c=xa(a,b);if(c)return c;a=ya(a);a[b]=Aa();return a[b].promise}function xa(a,b){var c=ya(a)[b];if(c){if(c.promise)return c.promise;w(a,b);return c.promise=Promise.resolve(c.obj)}return null}function ya(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}function va(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}
function Aa(){var a=new sa,b=a.promise,c=a.resolve;a=a.reject;b.catch(function(){});return{obj:null,promise:b,resolve:c,reject:a,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var Ba=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function Ca(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};var Da;var Ea=Object.prototype.hasOwnProperty;function B(){return Object.create(null)}function C(a){return a||{}}
function Fa(a,b){var c=[],d=[];d.push({t:a,s:b,d:0});for(a={};0<d.length;){b=d.shift();a.G=b.t;a.B=b.s;a.Y=b.d;if(c.includes(a.B))throw Error("Source object has a circular reference.");c.push(a.B);a.G!==a.B&&(10<a.Y?Object.assign(a.G,a.B):Object.keys(a.B).forEach(function(a){return function(b){var c=a.B[b];if(Ea.call(a.G,b)){var e=a.G[b];if("[object Object]"===ma.call(c)&&"[object Object]"===ma.call(e)){d.push({t:e,s:c,d:a.Y+1});return}}a.G[b]=c}}(a)));a={B:a.B,G:a.G,Y:a.Y}}};function D(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function Ga(a,b){for(var c=[],d=a.parentElement;d;d=d.parentElement)b(d)&&c.push(d);return c}function Ha(a){var b="fieldset";/^[\w-]+$/.test(b);b=b.toUpperCase();return Ga(a,function(a){return a.tagName==b})}function E(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)};function Ia(a,b,c){var d=wa(a,b);if(d)return d;var e=y(a);return e.waitForBodyOpen().then(function(){var a=e.win;var b=e.win.document.head;if(b){var d={};b=b.querySelectorAll("script[custom-element],script[custom-template]");for(var l=0;l<b.length;l++){var n=b[l];n=n.getAttribute("custom-element")||n.getAttribute("custom-template");d[n]=!0}d=Object.keys(d)}else d=[];return d.includes(c)?v(a,"extensions").waitForExtension(a,c):p()}).then(function(){var d=e.win;return d.__AMP_EXTENDED_ELEMENTS&&d.__AMP_EXTENDED_ELEMENTS[c]?
za(z(a),b):null})};function F(a){return x(a,"mutator")};var G,Ja="Webkit webkit Moz moz ms O o".split(" ");function Ka(a,b,c){var d=a.style;if(!D(b,"--")){G||(G=B());var e=G[b];if(!e){e=b;if(void 0===d[b]){var f=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var g=0;g<Ja.length;g++){var h=Ja[g]+f;if(void 0!==d[h]){f=h;break b}}f=""}void 0!==d[f]&&(e=f)}G[b]=e}b=e}b&&(D(b,"--")?a.style.setProperty(b,c):a.style[b]=c)}function La(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};var H;function Ma(a,b,c){var d=a,e=c;var f=function(a){try{return e(a)}catch(l){throw self.__AMP_REPORT_ERROR(l),l;}};var g=Na();d.addEventListener(b,f,g?void 0:!1);return function(){d&&d.removeEventListener(b,f,g?void 0:!1);f=d=e=null}}function Na(){if(void 0!==H)return H;H=!1;try{var a={get capture(){H=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return H};function I(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a}function Oa(a,b,c){return Ma(a,b,c)}function Pa(a,b){var c=b,d=Ma(a,"mouseup",function(a){try{c(a)}finally{c=null,d()}});return d}function Qa(a){var b,c=new Promise(function(c){b=Pa(a,c)});c.then(b,b);return c};function Ra(a,b){function c(c){f=null;e=a.setTimeout(d,100);b.apply(null,c)}function d(){e=0;f&&c(f)}var e=0,f=null;return function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];e?f=b:c(b)}};function Sa(a){var b=a.getRootNode();this.S=b.ownerDocument||b;this.j=this.S.defaultView;this.pa=x(a,"viewport");this.U=[];this.U.push(Oa(b,"input",function(a){a=a.target;"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&Ta(a)}));this.U.push(Oa(b,"mousedown",function(a){1==a.which&&(a=a.target,"TEXTAREA"==a.tagName&&Ua(a))}));var c=b.querySelectorAll("textarea");this.U.push(Oa(b,"amp:dom-update",function(){c=b.querySelectorAll("textarea")}));var d=Ra(this.j,function(a){a.relayoutAll&&Va(c)});this.U.push(this.pa.onResize(d));
Wa(c)}function Xa(a){function b(){var b=c.querySelector("textarea[autoexpand]");b&&!d?d=new Sa(a):!b&&d&&(d.dispose(),d=null)}var c=a.getRootNode(),d=null;Ma(c,"amp:dom-update",b);b()}Sa.prototype.dispose=function(){this.U.forEach(function(a){return a()})};
function Wa(a){Promise.all(na(a).map(function(a){return Ya(a).then(function(b){b&&(t().warn("AMP-FORM",'"textarea[autoexpand]" with initially scrolling content will not autoexpand.\nSee https://github.com/ampproject/amphtml/issues/20839'),a.removeAttribute("autoexpand"))})}))}function Ya(a){return F(a).measureElement(function(){return a.scrollHeight>a.clientHeight})}function Va(a){E(a,function(a){"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&Ta(a)})}
function Ua(a){var b=F(a);Promise.all([b.measureElement(function(){return a.scrollHeight}),Qa(a)]).then(function(c){var d=c[0],e=0;return b.measureMutateElement(a,function(){e=a.scrollHeight},function(){d!=e&&a.removeAttribute("autoexpand")})})}
function Ta(a){var b=F(a),c=a.ownerDocument.defaultView,d=0,e=0,f=0,g=$a(a);b.measureMutateElement(a,function(){var b=c.getComputedStyle(a)||B();e=a.scrollHeight;var g=parseInt(b.getPropertyValue("max-height"),10);f=isNaN(g)?Infinity:g;d="content-box"==b.getPropertyValue("box-sizing")?-parseInt(b.getPropertyValue("padding-top"),10)+-parseInt(b.getPropertyValue("padding-bottom"),10):parseInt(b.getPropertyValue("border-top-width"),10)+parseInt(b.getPropertyValue("border-bottom-width"),10)},function(){return g.then(function(b){a.classList.toggle("i-amphtml-textarea-max",
b+d>f);if("iAmphtmlHasExpanded"in a.dataset||e<=b)a.dataset.iAmphtmlHasExpanded="",Ka(a,"height",b+d+"px")})})}
function $a(a){var b=a.ownerDocument,c=b.defaultView,d=b.body,e=F(a),f=a.cloneNode(!1);f.classList.add("i-amphtml-textarea-clone");var g=0,h=0,l=!1;return e.measureMutateElement(d,function(){var b=c.getComputedStyle(a)||B(),d=parseInt(b.getPropertyValue("max-height"),10);g=parseInt(b.getPropertyValue("width"),10);l=isNaN(d)||a.scrollHeight<d},function(){l&&(a.scrollTop=0);Ka(f,"width",g+"px");b.body.appendChild(f)}).then(function(){return e.measureMutateElement(d,function(){h=f.scrollHeight},function(){f.parentElement&&
f.parentElement.removeChild(f)})}).then(function(){return h})};function J(a){for(var b=a.elements,c={},d=/^(?:input|select|textarea)$/i,e=/^(?:submit|button|image|file|reset)$/i,f=/^(?:checkbox|radio)$/i,g={},h=0;h<b.length;g={F:g.F},h++){var l=b[h],n=l,Xb=n.checked;g.F=n.name;var Yb=n.multiple,Zb=n.options,$b=n.tagName,Za=n.type;n=n.value;!g.F||ab(l)||!d.test($b)||e.test(Za)||f.test(Za)&&!Xb||(void 0===c[g.F]&&(c[g.F]=[]),Yb?E(Zb,function(a){return function(b){b.selected&&c[a.F].push(b.value)}}(g)):c[g.F].push(n))}var O=bb(a);O&&O.name&&(a=O.name,void 0===c[a]&&
(c[a]=[]),c[O.name].push(O.value));Object.keys(c).forEach(function(a){0==c[a].length&&delete c[a]});return c}function bb(a){var b=a.elements,c=b.length,d=a.ownerDocument.activeElement,e=null;for(a=0;a<c;a++){var f=b[a],g=f.type;if("BUTTON"==f.tagName||"submit"==g)if(e||(e=f),d==f)return d}return e}function ab(a){if(a.disabled)return!0;a=Ha(a);for(var b=0;b<a.length;b++)if(a[b].disabled)return!0;return!1}
function cb(a){switch(a.type){case "select-multiple":case "select-one":a=a.options;for(var b=0;b<a.length;b++)if(a[b].selected!==a[b].defaultSelected)return!1;break;case "checkbox":case "radio":return a.checked===a.defaultChecked;default:return a.value===a.defaultValue}return!0};function db(a,b){return a.hasAttribute("verify-xhr")?new eb(a,b):new fb(a)}function K(a){this.h=a}K.prototype.onCommit=function(){gb(this);a:{var a=this.h.elements;for(var b=0;b<a.length;b++){var c=a[b];if(!c.disabled&&!cb(c)){a=!0;break a}}a=!1}return a?this.Aa():Promise.resolve({updatedElements:[],errors:[]})};K.prototype.Aa=function(){return Promise.resolve({updatedElements:[],errors:[]})};function gb(a){(a=a.h.elements)&&E(a,function(a){a.setCustomValidity("")})}
function fb(){K.apply(this,arguments)}m(fb,K);function eb(a,b){this.h=a;this.ba=b;this.X=null;this.wa=[]}m(eb,K);eb.prototype.Aa=function(){var a=this,b=this.ba().then(function(){return[]},function(a){return hb(a)});return ib(this,b).then(function(b){return jb(a,b)})};function ib(a,b){if(!a.X){a.X=new ua;var c=function(){return a.X=null};a.X.then(c,c)}return a.X.add(b)}
function jb(a,b){var c=[],d=a.wa;a.wa=b;for(var e=0;e<b.length;e++){var f=b[e],g=t().assertString(f.name,"Verification errors must have a name property");f=t().assertString(f.message,"Verification errors must have a message property");g=t().assertElement(a.h.querySelector('[name="'+g+'"]'),"Verification error name property must match a field name");g.checkValidity()&&(g.setCustomValidity(f),c.push(g))}var h=d.filter(function(a){return b.every(function(b){return a.name!==b.name})}).map(function(b){return a.h.querySelector('[name="'+
b.name+'"]')});return{updatedElements:c.concat(h),errors:b}}function hb(a){return(a=a.response)?a.json().then(function(a){return a.verifyErrors||[]},function(){return[]}):Promise.resolve([])};function kb(a,b){var c=v(a,"platform");return c.isIos()&&11==c.getMajorVersion()?new lb(b):FormData.prototype.entries&&FormData.prototype.delete?new L(b):new M(b)}function M(a){this.C=a?J(a):B()}M.prototype.append=function(a,b){var c=String(a);this.C[c]=this.C[c]||[];this.C[c].push(String(b))};M.prototype.delete=function(a){delete this.C[a]};
M.prototype.entries=function(){var a=this,b=[];Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.push([c,a])})});var c=0;return{next:function(){return c<b.length?{value:b[c++],done:!1}:{value:void 0,done:!0}}}};M.prototype.getFormData=function(){var a=this,b=new FormData;Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.append(c,a)})});return b};function L(a){this.D=new FormData(a);a&&(a=bb(a))&&a.name&&this.append(a.name,a.value)}
L.prototype.append=function(a,b){this.D.append(a,b)};L.prototype.delete=function(a){this.D.delete(a)};L.prototype.entries=function(){return this.D.entries()};L.prototype.getFormData=function(){return this.D};function lb(a){L.call(this,a);var b=this;a&&E(a.elements,function(a){"file"==a.type&&0==a.files.length&&(b.D.delete(a.name),b.D.append(a.name,new Blob([]),""))})}m(lb,L);
lb.prototype.append=function(a,b,c){b&&"object"==typeof b&&""==b.name&&0==b.size?this.D.append(a,new Blob([]),c||""):this.D.append(a,b)};var mb={INPUT:!0,SELECT:!0,TEXTAREA:!0};function nb(a,b){this.h=a;this.j=b;this.R=0;this.K=B();this.oa=null;this.Ca=this.da=!1;this.ma();for(a=0;a<this.h.elements.length;++a)ob(this,this.h.elements[a]);N(this)}k=nb.prototype;k.onSubmitting=function(){this.da=!0;N(this)};k.onSubmitError=function(){this.da=!1;N(this)};k.onSubmitSuccess=function(){this.da=!1;this.oa=kb(this.j,this.h).getFormData();this.K=B();this.R=0;N(this)};
function N(a){var b=0<a.R&&!a.da;if(b!==a.Ca){a.h.classList.toggle("amp-form-dirty",b);var c=I(a.j,"amp:form-dirtiness-change",C({isDirty:b}),{bubbles:!0});a.h.dispatchEvent(c)}a.Ca=b}k.ma=function(){this.h.addEventListener("input",this.va.bind(this));this.h.addEventListener("reset",this.Ja.bind(this));this.h.addEventListener("amp:form-value-change",this.va.bind(this))};k.va=function(a){ob(this,a.target);N(this)};k.Ja=function(){this.K=B();this.R=0;N(this)};
function ob(a,b){var c=b.hidden;if(mb[b.tagName]&&b.name&&!c&&!ab(b)){a:switch(b.tagName){case "INPUT":c="checkbox"==b.type||"radio"==b.type?!b.checked:!b.value;break a;case "TEXTAREA":c=!b.value;break a;case "SELECT":c=!1;break a;default:throw Error("isFieldEmpty: "+b.tagName+" is not a supported field element.");}(c=c||cb(b))||(a.oa?(c=b.value,c=a.oa.get(b.name)===c):c=!1);c?(b=b.name,a.K[b]&&(a.K[b]=!1,--a.R)):(b=b.name,a.K[b]||(a.K[b]=!0,++a.R))}};function pb(){this.o=null}k=pb.prototype;k.add=function(a){var b=this;this.o||(this.o=[]);this.o.push(a);return function(){b.remove(a)}};k.remove=function(a){this.o&&(a=this.o.indexOf(a),-1<a&&this.o.splice(a,1))};k.removeAll=function(){this.o&&(this.o.length=0)};k.fire=function(a){if(this.o)for(var b=this.o,c=0;c<b.length;c++)(0,b[c])(a)};k.getHandlerCount=function(){return this.o?this.o.length:0};function qb(){this.ua=new pb}qb.prototype.beforeSubmit=function(a){return this.ua.add(a)};qb.prototype.fire=function(a){this.ua.fire(a)};function rb(){this.Ga=100;this.ga=this.na=0;this.$=Object.create(null)}rb.prototype.has=function(a){return!!this.$[a]};rb.prototype.get=function(a){var b=this.$[a];if(b)return b.access=++this.ga,b.payload};rb.prototype.put=function(a,b){this.has(a)||this.na++;this.$[a]={payload:b,access:this.ga};if(!(this.na<=this.Ga)){ra().warn("lru-cache","Trimming LRU cache");a=this.$;var c=this.ga+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.na--)}};var sb=C({c:!0,v:!0,a:!0,ad:!0}),tb,ub,vb=/[?&]amp_js[^&]*/,wb=/[?&]amp_gsa[^&]*/,xb=/[?&]amp_r[^&]*/,yb=/[?&]amp_kit[^&]*/,zb=/[?&]usqp[^&]*/;
function P(a){tb||(tb=self.document.createElement("a"),ub=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new rb));var b=ub,c=tb;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}function Ab(a,b,c){if(!b)return a;var d=a.split("#",2),e=d[0].split("?",2),f=e[0]+(e[1]?c?"?"+b+"&"+e[1]:"?"+e[1]+"&"+b:"?"+b);return f+=d[1]?"#"+d[1]:""}
function Bb(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(Array.isArray(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")}function Cb(a){"string"==typeof a&&(a=P(a));return qa.cdnProxyRegex.test(a.origin)};var Db=["GET","POST"];function Q(a,b){this.L=a;this.A=b;this.Na="amp-form"}Q.prototype.isEnabled=function(){var a=this.L.getAmpDoc();return a.isSingleDoc()&&a.getRootNode().documentElement.hasAttribute("allow-viewer-render-template")?this.L.hasCapability("viewerRenderTemplate"):!1};Q.prototype.assertTrustedViewer=function(a){return this.L.isTrustedViewer().then(function(b){u(b,"Refused to attempt SSR in untrusted viewer: ",a)})};
Q.prototype.ssr=function(a,b,c,d){var e=this;c=void 0===c?null:c;d=void 0===d?{}:d;var f=c,g=d,h;f||(h=this.A.maybeFindTemplate(a));return this.assertTrustedViewer(a).then(function(){return e.L.sendMessageAwaitResponse("viewerRenderTemplate",Eb(e,b,h,f,g))})};
Q.prototype.applySsrOrCsrTemplate=function(a,b){var c=this;if(this.isEnabled()){u("string"===typeof b.html,"Server side html response must be defined");var d=this.assertTrustedViewer(a).then(function(){return c.A.findAndSetHtmlForTemplate(a,b.html)})}else d=Array.isArray(b)?this.A.findAndRenderTemplateArray(a,b):this.A.findAndRenderTemplate(a,b);return d};
function Eb(a,b,c,d,e){var f=e=void 0===e?{}:e,g=C({type:a.Na}),h=d&&d.successTemplate?d.successTemplate:c;h&&(g.successTemplate={type:"amp-mustache",payload:h.innerHTML});var l=d&&d.errorTemplate?d.errorTemplate:null;l&&(g.errorTemplate={type:"amp-mustache",payload:l.innerHTML});f&&Object.assign(g,f);a=b.xhrUrl;c=b.fetchOpt;b=Object.assign({},c);if((d=c.body)&&"function"==typeof d.getFormData){c=c.body;b.headers["Content-Type"]="multipart/form-data;charset=utf-8";c=c.entries();d=[];for(e=c.next();!e.done;e=
c.next())d.push(e.value);b.body=d}return C({originalRequest:{input:a,init:b},ampComponent:g})};function Fb(a,b){this.la=b;this.pa=x(a,"viewport");this.Ba=v(a.win,"vsync");this.ja=null;this.ia="";this.ea=!1;this.J=a.win.document.createElement("div");La(this.J,!1);this.J.classList.add("i-amphtml-validation-bubble");this.J.__BUBBLE_OBJ=this;a.getBody().appendChild(this.J)}Fb.prototype.isActiveOn=function(a){return this.ea&&a==this.ja};Fb.prototype.hide=function(){this.ea&&(this.ea=!1,this.ja=null,this.ia="",this.Ba.run({measure:void 0,mutate:Gb},{bubbleElement:this.J}))};
Fb.prototype.show=function(a,b){this.isActiveOn(a)&&b==this.ia||(this.ea=!0,this.ja=a,this.ia=b,this.Ba.run({measure:Hb,mutate:Ib},{message:b,targetElement:a,bubbleElement:this.J,viewport:this.pa,id:this.la}))};function Gb(a){a.bubbleElement.removeAttribute("aria-alert");a.bubbleElement.removeAttribute("role");for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);La(a.bubbleElement,!1)}function Hb(a){a.targetRect=a.viewport.getLayoutRect(a.targetElement)}
function Ib(a){for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);var c=a.bubbleElement.ownerDocument.createElement("div");c.id="bubble-message-"+a.id;c.textContent=a.message;a.bubbleElement.setAttribute("aria-labeledby",c.id);a.bubbleElement.setAttribute("role","alert");a.bubbleElement.setAttribute("aria-live","assertive");a.bubbleElement.appendChild(c);La(a.bubbleElement,!0);b=a.bubbleElement;a={top:a.targetRect.top-10+"px",left:a.targetRect.left+a.targetRect.width/2+"px"};for(var d in a)Ka(b,
d,a[d])};var Jb,Kb,Lb=0;function R(a){this.form=a;this.ampdoc=y(a);this.mutator=F(a);this.root=this.ampdoc.getRootNode();this.ca=null}k=R.prototype;k.report=function(){};k.onBlur=function(){};k.onInput=function(){};k.inputs=function(){return this.form.querySelectorAll("input,select,textarea")};
k.checkInputValidity=function(a){if("TEXTAREA"===a.tagName&&a.hasAttribute("pattern")&&(a.checkValidity()||"Please match the requested format."===a.validationMessage)){var b=a.getAttribute("pattern"),c=(new RegExp("^"+b+"$","m")).test(a.value);a.setCustomValidity(c?"":"Please match the requested format.")}return a.checkValidity()};k.checkFormValidity=function(a){Mb(this,a);return a.checkValidity()};k.reportFormValidity=function(a){Mb(this,a);return a.reportValidity()};
function Mb(a,b){E(b.elements,function(b){"TEXTAREA"==b.tagName&&a.checkInputValidity(b)})}k.fireValidityEventIfNecessary=function(){var a=this.ca;this.ca=this.checkFormValidity(this.form);if(a!==this.ca){var b=I(this.form.ownerDocument.defaultView,this.ca?"valid":"invalid",null,{bubbles:!0});this.form.dispatchEvent(b)}};function Nb(){R.apply(this,arguments)}m(Nb,R);Nb.prototype.report=function(){this.reportFormValidity(this.form);this.fireValidityEventIfNecessary()};
function S(a){R.call(this,a);var b="i-amphtml-validation-bubble-"+Lb++;this.V=new Fb(this.ampdoc,b)}m(S,R);S.prototype.report=function(){for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){a[b].focus();this.V.show(a[b],a[b].validationMessage);break}this.fireValidityEventIfNecessary()};S.prototype.onBlur=function(a){"submit"!=a.target.type&&this.V.hide()};
S.prototype.onInput=function(a){a=a.target;this.V.isActiveOn(a)&&(this.checkInputValidity(a)?(a.removeAttribute("aria-invalid"),this.V.hide()):(a.setAttribute("aria-invalid","true"),this.V.show(a,a.validationMessage)))};function T(a){R.call(this,a);this.Qa=this.form.id?this.form.id:String(Date.now()+Math.floor(100*Math.random()));this.Fa=0}m(T,R);k=T.prototype;k.reportInput=function(a){var b=Ob(a);b&&this.showValidationFor(a,b)};k.hideAllValidations=function(){for(var a=this.inputs(),b=0;b<a.length;b++)this.hideValidationFor(a[b])};
k.getValidationFor=function(a,b){if(!a.id)return null;var c=a.validationMessage;c="TEXTAREA"===a.tagName&&"customError"===b&&"Please match the requested format."===c?"patternMismatch":b;var d="__AMP_VALIDATION_"+c;d in a||(a[d]=this.root.querySelector("[visible-when-invalid="+c+"][validation-for="+(a.id+"]")));return a[d]};
k.showValidationFor=function(a,b){var c=this.getValidationFor(a,b);if(c){c.textContent.trim()||(c.textContent=a.validationMessage);a.__AMP_VISIBLE_VALIDATION=c;var d=c.getAttribute("id");d||(d="i-amphtml-aria-desc-"+this.Qa+"-"+this.Fa++,c.setAttribute("id",d));a.setAttribute("aria-invalid","true");a.setAttribute("aria-describedby",d);this.mutator.mutateElement(c,function(){return c.classList.add("visible")})}};
k.hideValidationFor=function(a){var b=this.getVisibleValidationFor(a);b&&(delete a.__AMP_VISIBLE_VALIDATION,a.removeAttribute("aria-invalid"),a.removeAttribute("aria-describedby"),this.mutator.mutateElement(b,function(){return b.classList.remove("visible")}))};k.getVisibleValidationFor=function(a){return a.__AMP_VISIBLE_VALIDATION};k.shouldValidateOnInteraction=function(){throw Error("Not Implemented");};
k.onInteraction=function(a){a=a.target;var b=!!a.checkValidity&&this.shouldValidateOnInteraction(a);this.hideValidationFor(a);b&&!this.checkInputValidity(a)&&this.reportInput(a)};k.onBlur=function(a){this.onInteraction(a)};k.onInput=function(a){this.onInteraction(a)};function Pb(){T.apply(this,arguments)}m(Pb,T);Pb.prototype.report=function(){this.hideAllValidations();for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){this.reportInput(a[b]);a[b].focus();break}this.fireValidityEventIfNecessary()};
Pb.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function U(){T.apply(this,arguments)}m(U,T);U.prototype.report=function(){this.hideAllValidations();for(var a=null,b=this.inputs(),c=0;c<b.length;c++)this.checkInputValidity(b[c])||(a=a||b[c],this.reportInput(b[c]));a&&a.focus();this.fireValidityEventIfNecessary()};U.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function Qb(){T.apply(this,arguments)}m(Qb,T);
Qb.prototype.shouldValidateOnInteraction=function(){return!0};Qb.prototype.onInteraction=function(a){T.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};function Rb(){U.apply(this,arguments)}m(Rb,U);Rb.prototype.shouldValidateOnInteraction=function(){return!0};Rb.prototype.onInteraction=function(a){U.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};
function Sb(a){switch(a.getAttribute("custom-validation-reporting")){case "as-you-go":return new Qb(a);case "show-all-on-submit":return new U(a);case "interact-and-submit":return new Rb(a);case "show-first-on-submit":return new Pb(a)}a.ownerDocument&&void 0===Jb&&(Jb=!!document.createElement("form").reportValidity);return Jb?new Nb(a):new S(a)}
function Ob(a){var b=["badInput"];for(c in a.validity)b.includes(c)||b.push(c);var c=b.filter(function(b){return!0===a.validity[b]});return c.length?c[0]:null};function Tb(a){var b=a.ownerDocument.defaultView;b.FormProxy||(b.FormProxy=Ub(b));var c=new b.FormProxy(a);"action"in c||Vb(a,c);a.$p=c}
function Ub(a){function b(a){this.h=a}var c=b.prototype,d=a.Object,e=d.prototype;[a.HTMLFormElement,a.EventTarget].reduce(function(a,b){for(b=b&&b.prototype;b&&b!==e&&!(0<=a.indexOf(b));)a.push(b),b=d.getPrototypeOf(b);return a},[]).forEach(function(b){var d={},f;for(f in b){d.w=a.Object.getOwnPropertyDescriptor(b,f);if(d.w&&f.toUpperCase()!=f&&!D(f,"on")&&!e.hasOwnProperty.call(c,f))if("function"==typeof d.w.value)d.fa=d.w.value,c[f]=function(a){return function(){return a.fa.apply(this.h,arguments)}}(d);
else{var l={};d.w.get&&(l.get=function(a){return function(){return a.w.get.call(this.h)}}(d));d.w.set&&(l.set=function(a){return function(b){return a.w.set.call(this.h,b)}}(d));a.Object.defineProperty(c,f,l)}d={fa:d.fa,w:d.w}}});return b}
function Vb(a,b){var c=a.ownerDocument.defaultView.HTMLFormElement.prototype.cloneNode.call(a,!1),d={},e;for(e in c){d.l=e;if(!(d.l in b||d.l.toUpperCase()==d.l||D(d.l,"on"))){d.m=Wb[d.l];var f=a[d.l];if(d.m)if(d.m.access==V){d.N=void 0;if(f&&f.nodeType){var g=c=f,h=g.nextSibling;g=g.parentNode;g.removeChild(c);try{d.N=a[d.l]}finally{g.insertBefore(c,h)}}else d.N=f;Object.defineProperty(b,d.l,{get:function(a){return function(){return a.N}}(d)})}else d.m.access==W&&(d.O=d.m.attr||d.l,Object.defineProperty(b,
d.l,{get:function(c){return function(){var d=b.getAttribute(c.O);return null==d&&void 0!==c.m.def?c.m.def:c.m.type==ac?"true"===d:c.m.type==bc?null!=d:c.m.type==cc?(d=d||"",A(a,"url").parse(d).href):d}}(d),set:function(a){return function(c){a.m.type==bc&&(c=c?"":null);null!=c?b.setAttribute(a.O,c):b.removeAttribute(a.O)}}(d)}));else Object.defineProperty(b,d.l,{get:function(b){return function(){return a[b.l]}}(d),set:function(b){return function(c){a[b.l]=c}}(d)})}d={N:d.N,O:d.O,m:d.m,l:d.l}}}
var W=1,V=2,cc=1,ac=2,bc=3,Wb={acceptCharset:{access:W,attr:"accept-charset"},accessKey:{access:W,attr:"accesskey"},action:{access:W,type:cc},attributes:{access:V},autocomplete:{access:W,def:"on"},children:{access:V},dataset:{access:V},dir:{access:W},draggable:{access:W,type:ac,def:!1},elements:{access:V},encoding:{access:V},enctype:{access:W},hidden:{access:W,type:bc,def:!1},id:{access:W,def:""},lang:{access:W},localName:{access:V},method:{access:W,def:"get"},name:{access:W},noValidate:{access:W,
attr:"novalidate",type:bc,def:!1},prefix:{access:V},spellcheck:{access:W},style:{access:V},target:{access:W,def:""},title:{access:W},translate:{access:W}};function dc(a,b){var c=a.getHeadNode(),d=ec(c,fc(c));if(b){var e=a.getRootNode();if(gc(e,d))b(d);else var f=setInterval(function(){gc(e,d)&&(clearInterval(f),b(d))},4)}}
function ec(a,b){var c=a.__AMP_CSS_SM;c||(c=a.__AMP_CSS_SM=B());var d=hc(a,c,"amp-extension=amp-form");if(d)return d.textContent!==b&&(d.textContent=b),d;var e=(a.ownerDocument||a).createElement("style");e.textContent=b;var f=null;e.setAttribute("amp-extension","amp-form");b=f=hc(a,c,"amp-runtime");(b=void 0===b?null:b)?a.insertBefore(e,b.nextSibling):a.insertBefore(e,a.firstChild);return c["amp-extension=amp-form"]=e}
function hc(a,b,c){return b[c]?b[c]:(a=a.querySelector("style["+c+"]"))?b[c]=a:null}
function fc(a){return(a=a.__AMP_CSS_TR)?a('form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}textarea[autoexpand]:not(.i-amphtml-textarea-max){overflow:hidden!important}.i-amphtml-textarea-clone{visibility:hidden;position:absolute;top:-9999px;left:-9999px;height:0!important}.i-amphtml-validation-bubble{transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,0.5);max-width:200px;position:absolute;display:block;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:" ";position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{color:red}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/'):'form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}textarea[autoexpand]:not(.i-amphtml-textarea-max){overflow:hidden!important}.i-amphtml-textarea-clone{visibility:hidden;position:absolute;top:-9999px;left:-9999px;height:0!important}.i-amphtml-validation-bubble{transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,0.5);max-width:200px;position:absolute;display:block;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:" ";position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{color:red}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/'}
function gc(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++)if(c[a].ownerNode==b)return!0;return!1};function ic(a){var b=a.documentElement;return["\u26a14email","amp4email"].some(function(a){return b.hasAttribute(a)})};function jc(a,b,c){c=void 0===c?{}:c;var d=void 0===d?!0:d;var e=c;Ia(a,"amp-analytics-instrumentation","amp-analytics").then(function(c){c&&c.triggerEventForTarget(a,b,e,d)})};function kc(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};var lc=["amp-selector"];
function mc(a,b){var c=this;try{Tb(a)}catch(f){ra().error("amp-form","form proxy failed to install",f)}a.__AMP_FORM=this;this.la=b;this.S=a.ownerDocument;this.j=this.S.defaultView;this.Pa=v(this.j,"timer");this.za=A(a,"url-replace");this.ka=null;this.h=a;this.Ea=y(this.h);this.A=v(this.j,"templates");this.qa=v(this.j,"xhr");this.P=A(this.h,"action");this.ta=F(this.h);this.L=x(this.h,"viewer");this.T=new Q(this.L,this.A);this.H=(this.h.getAttribute("method")||"GET").toUpperCase();this.Oa=this.h.getAttribute("target");
this.M=nc(this,"action-xhr");this.Ua=nc(this,"verify-xhr");this.Ha=oc(this);this.ya=!this.h.hasAttribute("novalidate");this.h.setAttribute("novalidate","");this.ya||this.h.setAttribute("amp-novalidate","");this.h.classList.add("i-amphtml-form");this.I="initial";b=this.h.elements;for(var d=0;d<b.length;d++){var e=b[d].name;u("__amp_source_origin"!=e&&"__amp_form_verify"!=e,"Illegal input name, %s found: %s",e,b[d])}this.aa=new nb(this.h,this.j);this.W=Sb(this.h);this.Ra=db(this.h,function(){return pc(c)});
this.P.addToAllowlist("FORM",["clear","submit"],["email"]);this.P.installActionHandler(this.h,this.Da.bind(this));this.ma();qc(this);rc(this);this.ra=this.La=this.Ta=null;za(z(a),"form-submit-service").then(function(a){c.ra=a});this.Ia=this.S&&ic(this.S)}function nc(a,b){var c=a.h.getAttribute(b);if(c){var d=A(a.h,"url");d.assertHttpsUrl(c,a.h,b);u(!d.isProxyOrigin(c),"form %s should not be on AMP CDN: %s",b,a.h)}return c}
function oc(a){var b=a.h.getAttribute("enctype");if("application/x-www-form-urlencoded"===b||"multipart/form-data"===b)return b;null!==b&&t().warn("amp-form","Unexpected enctype: "+b+". Defaulting to 'multipart/form-data'.");return"multipart/form-data"}k=mc.prototype;k.getXssiPrefix=function(){return this.h.getAttribute("xssi-prefix")};
k.requestForFormFetch=function(a,b,c,d){var e=C({Accept:"application/json"});if("GET"==b||"HEAD"==b){sc(this);var f=J(this.h);d&&d.forEach(function(a){return delete f[a]});c&&Fa(f,c);var g=Ab(a,Bb(f))}else{g=a;if("application/x-www-form-urlencoded"===this.Ha){var h=Bb(J(this.h));e=C({Accept:"application/json","Content-Type":"application/x-www-form-urlencoded"})}else h=kb(this.j,this.h);d&&d.forEach(function(a){return h.delete(a)});for(var l in c)h.append(l,c[l])}return{xhrUrl:g,fetchOpt:C({body:h,
method:b,credentials:"include",headers:e})}};k.setXhrAction=function(a){this.M=a};k.Da=function(a){var b=this;if(!a.satisfiesTrust(2))return null;if("submit"==a.method)return tc(this).then(function(){return"submitting"!=b.I&&uc(b)?vc(b,a.trust,null):Promise.resolve(null)});"clear"===a.method&&wc(this);return null};function tc(a){if(a.ka)return a.ka;var b=a.h.querySelectorAll(lc.join(",")),c=na(b).map(function(a){return a.whenBuilt()});return a.ka=xc(a,c,2E3)}
k.ma=function(){var a=this;this.Ea.whenNextVisible().then(function(){var b=a.h.querySelector("[autofocus]");if(b)try{b.focus()}catch(c){}});this.h.addEventListener("submit",this.sa.bind(this),!0);this.h.addEventListener("blur",function(b){yc(b.target);a.W.onBlur(b)},!0);this.h.addEventListener("amp:form-value-change",function(b){yc(b.target);a.W.onInput(b)},!0);this.T.isEnabled()||this.h.addEventListener("change",function(b){a.Ra.onCommit().then(function(c){var d=c.errors;c.updatedElements.forEach(yc);
a.W.onBlur(b);"verifying"===a.I&&(d.length?(X(a,"verify-error"),Y(a,C({verifyErrors:d})).then(function(){zc(a,"verify-error",d,2)})):X(a,"initial"))})});this.h.addEventListener("input",function(b){yc(b.target);a.W.onInput(b)})};function qc(a){Ia(a.h,"inputmask","amp-inputmask").then(function(a){a&&a.install()})}
function Ac(a,b){Bc(a,"Form analytics not supported");var c=C({}),d=J(a.h),e;for(e in d)Object.prototype.hasOwnProperty.call(d,e)&&(c["formFields["+e+"]"]=d[e].join(","));c.formId=a.h.id;jc(a.h,b,c)}
function wc(a){a.h.reset();X(a,"initial");a.h.classList.remove("user-valid");a.h.classList.remove("user-invalid");var b=a.h.querySelectorAll(".user-valid, .user-invalid");E(b,function(a){a.classList.remove("user-valid");a.classList.remove("user-invalid")});var c=a.h.querySelectorAll(".visible[validation-for]");E(c,function(a){a.classList.remove("visible")});Cc(a.h)}
k.sa=function(a){if("submitting"==this.I||!uc(this))return a.stopImmediatePropagation(),a.preventDefault(),Promise.resolve(null);(this.M||"POST"==this.H)&&a.preventDefault();return vc(this,3,a)};
function vc(a,b,c){try{var d={form:a.h,actionXhrMutator:a.setXhrAction.bind(a)};a.ra.fire(d)}catch(l){ra().error("amp-form","Form submit service failed: %s",l)}var e=Dc(a),f=a.h.getElementsByClassName("i-amphtml-async-input");a.aa.onSubmitting();if(!a.M&&"GET"==a.H){Bc(a,"Non-XHR GETs not supported.");sc(a);if(0===f.length){for(d=0;d<e.length;d++)a.za.expandInputValueSync(e[d]);Ec(a,!c);a.aa.onSubmitSuccess();return p()}c&&c.preventDefault()}X(a,"submitting");var g=[],h=[];h.push(Fc(a,e));E(f,function(b){var c=
Gc(a,b);b.classList.contains("i-async-require-action")?g.push(c):h.push(c)});return Promise.all(g).then(function(){return xc(a,h,1E4).then(function(){if(a.M)var c=Hc(a,b);else"POST"==a.H?u(!1,"Only XHR based (via action-xhr attribute) submissions are supported for POST requests. %s",a.h):"GET"==a.H&&Ec(a,!0),c=p();return c},function(c){return Ic(a,c,b)})},function(c){return Ic(a,c,b)})}function Ic(a,b,c){var d={};b&&b.message&&(d.error=b.message);return Jc(a,b,d,c)}
function Dc(a){return a.h.querySelectorAll('[type="hidden"][data-amp-replace]')}function pc(a){if("submitting"===a.I)return p();X(a,"verifying");zc(a,"verify",null,3);return Fc(a,Dc(a)).then(function(){return Kc(a)})}function Hc(a,b){if(a.T.isEnabled())var c=Lc(a,b);else Mc(a,b),c=a.ba(a.M,a.H).then(function(c){return Nc(a,c,b)},function(c){return Oc(a,c,b)});return c}
function Lc(a,b){var c=J(a.h);return Y(a,c).then(function(){return a.P.trigger(a.h,"submit",null,b)}).then(function(){var b=a.requestForFormFetch(a.M,a.H),c=b.fetchOpt||{};var f=c.method;void 0===f?f="GET":(f=f.toUpperCase(),Db.includes(f));c.method=f;c.headers=c.headers||C({});b.fetchOpt=c;f=b.xhrUrl;c=(c=b.fetchOpt)||{};var g=a.j;g=g.origin||P(g.location.href).origin;f=P(f).origin;g==f&&(c.headers=c.headers||{},c.headers["AMP-Same-Origin"]="true");b.fetchOpt=c;f=a.j;c=b.xhrUrl;if(!1!==b.fetchOpt.ampCors){g=
P(c);g=la(g.search);u(!("__amp_source_origin"in g),"Source origin is not allowed in %s",c);f=f.location.href;"string"==typeof f&&(f=P(f));if(Cb(f)){g=f.pathname.split("/");u(sb[g[1]],"Unknown path prefix in url %s",f.href);var h=g[2],l="s"==h?"https://"+decodeURIComponent(g[3]):"http://"+decodeURIComponent(h);u(0<l.indexOf("."),"Expected a . in origin %s",l);g.splice(1,"s"==h?3:2);g=l+g.join("/");h=(h=f.search)&&"?"!=h?(h=h.replace(vb,"").replace(wb,"").replace(xb,"").replace(yb,"").replace(zb,"").replace(/^[?&]/,
""))?"?"+h:"":"";f=g+h+(f.hash||"")}else f=f.href;f=P(f).origin;f=encodeURIComponent("__amp_source_origin")+"="+encodeURIComponent(f);c=Ab(c,f,void 0)}b.xhrUrl=c;return a.T.ssr(a.h,b,Pc(a))}).then(function(c){return Qc(a,c,b)},function(c){var d={};c&&c.message&&(d.error=c.message);return Jc(a,c,d,b)})}
function Pc(a){var b,c=a.h.querySelector("[submit-success]");c&&(b=a.A.maybeFindTemplate(c));var d,e=a.h.querySelector("[submit-error]");e&&(d=a.A.maybeFindTemplate(e));return{successTemplate:b,errorTemplate:d}}function Qc(a,b,c){var d=b.init,e=kc(b.body,function(a){return t().error("amp-form","Failed to parse response JSON: %s",a)});return d&&(d=d.status,300<=d)?Jc(a,d,b,c,e):Rc(a,b,c,e)}
function Mc(a,b){Ac(a,"amp-form-submit");var c=J(a.h);Y(a,c).then(function(){a.P.trigger(a.h,"submit",null,b)})}function Fc(a,b){for(var c=[],d=0;d<b.length;d++)c.push(a.za.expandInputValueAsync(b[d]));return xc(a,c,100)}
function Gc(a,b){return b.getImpl().then(function(a){return a.getValue()}).then(function(c){var d=b.getAttribute("name");d=a.h.querySelector("input[name="+String(d).replace(Ba,Ca)+"]");if(!d){d=C({name:b.getAttribute("name"),hidden:"true"});var e=a.j.document.createElement("input"),f;for(f in d)e.setAttribute(f,d[f]);d=e}d.setAttribute("value",c);a.h.appendChild(d)})}
function Kc(a){var b=na(a.h.querySelectorAll("["+"no-verify".replace(Ba,Ca)+"]")).map(function(a){return a.name||a.id}),c={};return a.ba(a.Ua,a.H,(c.__amp_form_verify=!0,c),b)}k.ba=function(a,b,c,d){Bc(this,"XHRs should be proxied.");a=this.requestForFormFetch(a,b,c,d);return this.qa.fetch(a.xhrUrl,a.fetchOpt)};
function Nc(a,b,c){return a.qa.xssiJson(b,a.getXssiPrefix()).then(function(b){return Rc(a,b,c)},function(a){return t().error("amp-form","Failed to parse response JSON: %s",a)}).then(function(){Ac(a,"amp-form-submit-success");Sc(a,b)})}function Rc(a,b,c,d){X(a,"submit-success");return ta(function(){Y(a,b||{}).then(function(){zc(a,"submit-success",void 0===d?b:d,c-1);a.aa.onSubmitSuccess()})})}
function Oc(a,b,c){return(b&&b.response?a.qa.xssiJson(b.response,a.getXssiPrefix()).catch(function(){return null}):Promise.resolve(null)).then(function(d){Ac(a,"amp-form-submit-error");Jc(a,b,d,c);Sc(a,b.response)})}function Jc(a,b,c,d,e){X(a,"submit-error");t().error("amp-form","Form submission failed: %s",b);return ta(function(){Y(a,c).then(function(){zc(a,"submit-error",void 0===e?c:e,d-1);a.aa.onSubmitError()})})}function Ec(a,b){Ac(a,"amp-form-submit");b&&a.h.submit();X(a,"initial")}
function Bc(a,b){var c=a.T.isEnabled();u(!1===c,"[amp-form]: viewerRenderTemplate | %s",b)}function sc(a){var b=a.h.querySelectorAll("input[type=password],input[type=file]");u(0==b.length,"input[type=password] or input[type=file] may only appear in form[method=post]")}function uc(a){void 0===Kb&&(Kb=!!a.j.document.createElement("input").checkValidity);if(Kb){var b=Tc(a.h);if(a.ya)return a.W.report(),b}return!0}
function Sc(a,b){Bc(a,"Redirects not supported.");if(b&&b.headers){var c=b.headers.get("AMP-Redirect-To");if(c){u(!a.Ia,"Redirects not supported in AMP4Email.",a.h);u("_blank"!=a.Oa,"Redirecting to target=_blank using AMP-Redirect-To is currently not supported, use target=_top instead. %s",a.h);try{var d=A(a.h,"url");d.assertAbsoluteHttpOrHttpsUrl(c);d.assertHttpsUrl(c,"AMP-Redirect-To","Url")}catch(e){u(!1,"The `AMP-Redirect-To` header value must be an absolute URL starting with https://. Found %s",
c)}x(a.h,"navigation").navigateTo(a.j,c,"AMP-Redirect-To")}}}function zc(a,b,c,d){c=I(a.j,"amp-form."+b,C({response:c}));a.P.trigger(a.h,b,c,d)}function xc(a,b,c){return Promise.race([Promise.all(b),a.Pa.promise(c)])}
function X(a,b){var c=a.I;a.h.classList.remove("amp-form-"+c);a.h.classList.add("amp-form-"+b);var d=a.h.querySelector("["+c+"]");if(d){/^[\w-]+$/.test("i-amphtml-rendered");if(void 0!==Da)var e=Da;else{try{var f=d.ownerDocument,g=f.createElement("div"),h=f.createElement("div");g.appendChild(h);e=g.querySelector(":scope div")===h}catch(l){e=!1}e=Da=e}e?d=d.querySelector("> [i-amphtml-rendered]".replace(/^|,/g,"$&:scope ")):(d.classList.add("i-amphtml-scoped"),e="> [i-amphtml-rendered]".replace(/^|,/g,
"$&.i-amphtml-scoped "),e=d.querySelectorAll(e),d.classList.remove("i-amphtml-scoped"),d=void 0===e[0]?null:e[0]);d&&d.parentElement&&d.parentElement.removeChild(d)}a.I=b}
function Y(a,b){Array.isArray(b)&&(b={},t().warn("amp-form","Unexpected data type: "+b+". Expected non JSON array."));var c=a.h.querySelector("["+a.I+"]"),d=p();if(c){var e="rendered-message-"+a.la;c.setAttribute("role","alert");c.setAttribute("aria-labeledby",e);c.setAttribute("aria-live","assertive");a.A.hasTemplate(c)?d=a.T.applySsrOrCsrTemplate(c,b).then(function(b){if(Array.isArray(b))if(1===b.length)var d=b[0];else d=document.createElement("div"),b.forEach(function(a){return d.appendChild(a)});
else d=b;d.id=e;d.setAttribute("i-amphtml-rendered","");return a.ta.mutateElement(c,function(){c.appendChild(d);var b=I(a.j,"amp:dom-update",null,{bubbles:!0});c.dispatchEvent(b)})}):a.ta.mutateElement(c,function(){})}return d}
function rc(a){if(!Cb(a.j.location)&&a.h.hasAttribute("data-initialize-from-url")){var b=["SELECT","TEXTAREA"],c="color date datetime-local email hidden month number range search tel text time url week".split(" "),d=["checkbox","radio"],e=function(a,e){if(!a.hasAttribute("data-amp-replace")&&a.hasAttribute("data-allow-initialization")){e=f[e]||"";var g=a.getAttribute("type")||"text",h=a.tagName;"INPUT"===h?c.includes(g.toLocaleLowerCase())?a.value!==e&&(a.value=e):d.includes(g)&&(e=a.value===e,a.checked!==
e&&(a.checked=e)):b.includes(h)&&a.value!==e&&(a.value=e)}},f=la(a.j.location.search);Object.keys(f).forEach(function(b){var c=a.h.elements[b];c&&(c.nodeType===Node.ELEMENT_NODE?e(c,b):c.length&&E(c,function(a){return e(a,b)}))})}}k.Va=function(){return this.La};k.Xa=function(){return this.Ta};function Tc(a){var b=a.querySelectorAll("input,select,textarea,fieldset");E(b,function(a){return Z(a)});return Z(a)}
function Cc(a){var b=document.createElement("input"),c={},d;for(d in b.validity){c.Z=d;var e=a.querySelectorAll("."+String(c.Z).replace(Ba,Ca));E(e,function(a){return function(b){b.classList.remove(a.Z)}}(c));c={Z:c.Z}}}
function Z(a,b){var c=b=void 0===b?!1:b;if(!a.checkValidity)return!0;var d=!1;var e=a.classList.contains("user-valid")?"valid":a.classList.contains("user-invalid")?"invalid":"none";var f=a.checkValidity();"valid"!=e&&f?(a.classList.add("user-valid"),a.classList.remove("user-invalid"),d="invalid"==e):"invalid"==e||f||(a.classList.add("user-invalid"),a.classList.remove("user-valid"),d=!0);if(a.validity)for(var g in a.validity)a.classList.toggle(g,a.validity[g]);if(c&&d){e=Ha(a);for(g=0;g<e.length;g++)Z(e[g]);
a.form&&Z(a.form)}return f}function yc(a){Z(a,!0)}function Uc(a){this.Sa=Vc(a).then(function(){return Wc(a)})}Uc.prototype.whenInitialized=function(){return this.Sa};function Vc(a){var b=new sa;dc(a,b.resolve);return b.promise}function Wc(a){return a.whenReady().then(function(){var b=a.getRootNode();Xc(b.querySelectorAll("form"));Xa(a);Yc(b);Zc(b)})}function Xc(a){a&&E(a,function(a,c){a.__AMP_FORM||new mc(a,"amp-form-"+c)})}
function Yc(a){a.addEventListener("amp:dom-update",function(){Xc(a.querySelectorAll("form"))})}function Zc(a){a.addEventListener("keydown",function(a){if(!a.defaultPrevented&&"Enter"==a.key&&(a.ctrlKey||a.metaKey)&&"TEXTAREA"===a.target.tagName){var b=a.target.form,d=b?b.__AMP_FORM||null:null;d&&(d.sa(a),a.preventDefault())}})}(function(a){a.registerServiceForDoc("form-submit-service",qb);a.registerServiceForDoc("amp-form",Uc)})(self.AMP);
})});

//# sourceMappingURL=amp-form-0.1.js.map
